stages:
  - build
  - release

variables:
  GIT_DEPTH: 2

build:
  image: maven:3.8.1-jdk-11
  stage: build
  artifacts:
    paths:
    - target/documends-0.0.1.jar
    expire_in: 1 week
  script:
    - mvn clean install -Dmaven.test.skip=true
  only:
    - reports

release:
  image: docker:19.03.8
  stage: release
  dependencies: 
    - build
  only:
    - reports
  services:
    - docker:19.03.8-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - pwd
    - ls -l ./target/
    - echo Releasing $IMAGE_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
