version: '3.7'

services:
   db:
     image: postgres:12
     volumes:
       - postgres:/var/lib/postgresql/data
     restart: always
     environment:
       POSTGRES_PASSWORD: postgres 

   web-api:
     depends_on:
       - db
     image: registry.gitlab.com/pirai/documends:latest
     ports:
       - "8084:8084"
     restart: always
   
   adminer:
     depends_on:
       - db
     image: adminer
     ports:
       - "8080:8080"
     restart: always

volumes:
    postgres: {}
