package com.internaltools.util;

public interface AppConstants {
	String DEFAULT_PAGE_NUMBER = "0";
	String DEFAULT_PAGE_SIZE = "30";

	int MAX_PAGE_SIZE = 50;

	String DEFAULT_DISTANCE = "DEFAULT_DISTANCE";
	String DEFAULT_DISTANCE_UNITS = "DEFAULT_DISTANCE_UNITS";

	int ORDER_MAX_SEQ_NO = 9999;

	String ACTION_CREATE = "create";
	String ACTION_UPDATE = "update";
	String ACTION_DELETE = "delete";

	String PROMOTION_DISCOUNT = "discount";
	String PROMOTION_FREE = "free";
	String STRIPE_SUBSCRIPTION_PLAN_CODES = "STRIPE_SUBSCRIPTION_PLAN_CODES";
	String STRIPE_SERVICE_CHARGE_PERCENT = "STRIPE_SERVICE_CHARGE_PERCENT";
	String STRIPE_DOCUMENDS_PERCENT = "STRIPE_DOCUMENDS_PERCENT";
	String STRIPE_SERVICE_FIXED_FEE = "STRIPE_SERVICE_FIXED_FEE";
}
